### ISSUE TITLE
Youtube Music 1.1.2V problem!

### ISSUE THREAD

**Issue by martins-pirac** [patrickkfkan/volumio-ytmusic#4]
Good morning! 
This morning I noticed that Youtube Music throws the following error, see the picture.
I had a similar error last week, following your instructions I uninstalled the old version and installed 1.1.2V Stable and everything was fine.
Just did the identical steps, restarted volumio but the error persisted.

Have a nice day!
Thank you!

![Screenshot 2024-08-02 100008](https://github.com/user-attachments/assets/8bf2dddc-0d18-43b5-b21f-a37af77488fb)
![Screenshot 2024-08-02 100433](https://github.com/user-attachments/assets/578c7cc4-956d-4c63-a716-000bf3a7a704)

**Comment by patrickkfkan** [comment]
Fixed:

https://community.volumio.com/t/plugin-youtube-music/57647/200?u=patrickkfkan
